apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: example-app-nodejs-docker
  namespace: user1-petclinic
spec:
  host: example-app-nodejs-docker-demo-application-deployment.apps.cluster-rflkz.rflkz.sandbox998.opentlc.com
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: example-app-nodejs-docker
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
status: {}
